apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  ADMIN_URL: https://admin-staging.mi-empresa.ninja
  APP_DEBUG: "false"
  APP_ENV: staging
  APP_KEY: base64:UNHLxgCdJvQZyfCzO7Sdfdt/gLfU/pgkYMQLoAqf5o0=
  APP_NAME: Mi-empresa
  APP_URL: http://mi-empresa.local
  AWS_BUCKET: myawsmi-empresalocal
  AWS_DEFAULT_REGION: eu-west-1
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: mysql
  DB_DATABASE: mi-empresa
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USERNAME: root
  FILESYSTEM_DRIVER: s3
  GOOGLE_CALENDAR_AUTH_PROFILE: oauth
  GOOGLE_CALENDAR_ID: prueba@mi-empresa.com
  GTAG_ID: UA-207167081-1
  GTM_ID: GTM-WMR8V25
  LOG_CHANNEL: stack
  MAIL_ENCRYPTION: tls
  MAIL_FROM_ADDRESS: antonio@mi-empresa.com
  MAIL_FROM_NAME: Mi-empresa
  MAIL_HOST: smtp.mailtrap.io
  MAIL_MAILER: smtp
  MAIL_PORT: "2525"
  MAIL_USERNAME: 41e6a32f28bd24
  MAIL_USERNAME_MANAGER2: antonio@mi-empresa.com
  MAIL_USERNAME_MANAGER3: antonio@mi-empresa.com
  MAIL_USERNAME_MANAGER4: antonio@mi-empresa.com
  MAIL_USERNAME_MANAGER: antonio@mi-empresa.com
  REDIS_URL: redis://redis:6379
  SENTRY_LARAVEL_DSN: https://96fcaae44a584f83bbfe784aefbdfca1@o454678.ingest.sentry.io/5445082
  SENTRY_TRACES_SAMPLE_RATE: "1"
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
