resources:
- namespace.yaml
- ../base
namespace: staging
patchesStrategicMerge:
- config.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: web-secret
  behavior: replace
  envs:
  - .env.secret
